id: ID3735933
legacy_id: P007015
ocr_import_info:
  bdrc_scan_id: W15232
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:56:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T03:42:54.870693+00:00'
last_modified: 2022-08-27 11:43:16.360578
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W15232
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW15232
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་བཞིའི་སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ་རྒྱས་པ།
  author: བྲང་ཏི་དཔལ་ལྡན་འཚོ་བྱེད།
statistics:
  ocr_word_mean_confidence_index: 0.9452253024940414
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1GS65490:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS65490
      total_pages: 85
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS65490.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9452253024940414
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
