id: ID3735933
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:57:08+00:00'
last_modified: '2022-06-08T12:01:22.678223+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15232
  title: རྒྱུད་བཞིའི་སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6BE1:
      image_group_id: I1GS65490
      title: Volume 1 of rgyud bzhi'i spyi don shes bya rab gsal rgyas pa
      total_pages: 85
      order: 1
      base_file: 6BE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
