id: P007015
initial_creation_type: ocr
source_metadata:
  id: bdr:W15232
  title: རྒྱུད་བཞིའི་སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ་རྒྱས་པ།
  author: ''
  volumes:
    6461fdc886cd44689c2fd628a96aef29:
      image_group_id: I1GS65490
      title: ''
      volume_number: 1
      total_pages: 85
ebook_metadata:
  title: རྒྱུད་བཞིའི་སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ་རྒྱས་པ།
  author: ''
  sku: P007015
  cover: cover.jpg
  layers:
  - pagination
