id: P007015
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:20.732694
source_metadata:
  id: bdr:W15232
  title: རྒྱུད་བཞིའི་སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ་རྒྱས་པ།
  author: ''
  volumes:
    d4f6fb10c41147e6ae8733624877560a:
      image_group_id: I1GS65490
      title: Volume 1 of rgyud bzhi'i spyi don shes bya rab gsal rgyas pa
      volume_number: 1
      total_pages: 85
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
